name: CI/CD pipeline

# Déclencher le pipeline lorsqu'un commit est poussé sur la branche principale
on:
  push:
    branches:
      - release
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code source depuis le dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer les dépendances et construire l'application React
      - name: Build React app
        run: |
          npm install
          npm run build

      # Configurer AWS CLI pour accéder au bucket S3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Redirection vers l'URL S3
      - name: Configure S3 website redirection
        run: |
          aws s3api put-bucket-website --bucket www.password-generator.mia-tech.com --website-configuration '{
            "IndexDocument": {"Suffix": "index.html"},
            "ErrorDocument": {"Key": "index.html"}
          }'

      # Déployer l'application sur le bucket S3
      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://gwww.password-generator.mia-tech.com --delete

      # Afficher l'URL de l'application déployée
      - name: Display app URL
        run: |
          echo "http://www.password-generator.mia-tech.com.s3-website.eu-central-1.amazonaws.com"
