name: CI/CD pipeline

# Déclencher le pipeline lorsqu'un commit est poussé sur la branche principale
on:
  push:
    branches:
      - release
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code source depuis le dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer les dépendances et construire l'application React
      - name: Build React app
        run: |
          npm install
          npm run build

      # Creation de l'image docker et push sur sur un registry
      - name: Build docker image
        run: docker build . --file dockerfile --tag password-genarare:${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            hermesn/password-genarare:latest 
            hermesn/password-genarare:${{ github.sha }}
      # Deployment en production
      - name: deployement en production
        run: |
          docker-compose -f docker-compose.yaml up -d
